### ISSUE TITLE
Sorting problem in Grid

### ISSUE THREAD

**Issue by dbrezoev** [aurelia-components/examples#2]
Consider if in base-store.js the following method should be: 
changeSortProcessingOrder(sort) {
    let index = this.sortProcessingOrder.findIndex((el, index) => {
      if (**el.name === sort.name**) {  <------------ // it was el.column == sort.column
        return true;
      }
........
}

When used with backend sorting it sends the same sorting options for one column over and over.
by: Niki, Dobromir x 2

**Comment by moshensky** [comment]
fix test and push :)

**Comment by moshensky** [comment]
they can't be compared by name, because if you have two columns representing same data sort will fail.

**Comment by moshensky** [comment]
Will be fixed today.
